saje1:
	@python breakpoints/bp1/saje_project/src/server.py

saje2:
	@python breakpoints/bp2/saje_project/src/server.py

saje3:
	@python breakpoints/bp3/saje_project/src/server.py

pretty:
	black src
	isort src
